services:
  - type: web
    name: fastapi-app
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    # ポート番号はコード側の os.getenv("PORT", 10000) で対応

  - type: private
    name: postgres-service
    runtime: image
    plan: free
    image:
      url: postgres:16
    disk:
      name: postgres-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    ports:
      - port: 5432
