services:
  - type: web
    name: fastapi-app
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: postgres_service
      - key: DB_USER
        value: sampleuser
      - key: DB_PASSWORD
        value: samplepass
      - key: DB_NAME
        value: sampledb
      - key: PORT
        value: "10000"
    healthCheckPath: /

  - type: private
    name: postgres-service
    runtime: image
    plan: free
    image:
      url: postgres:16
    envVars:
      - key: POSTGRES_DB
        value: sampledb
      - key: POSTGRES_USER
        value: sampleuser
      - key: POSTGRES_PASSWORD
        value: samplepass
    disk:
      name: postgres-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    ports:
      - port: 5432
