services:
  - type: web
    name: fastapi-app
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql-service
      - key: DB_USER
        value: sampleuser
      - key: DB_PASSWORD
        value: samplepass
      - key: DB_NAME
        value: sampledb
      - key: PORT
        value: "10000"
    healthCheckPath: /

  - type: private
    name: mysql-service
    runtime: image
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: sampledb
      - key: MYSQL_USER
        value: sampleuser
      - key: MYSQL_PASSWORD
        value: samplepass
      - key: MYSQL_ROOT_PASSWORD
        value: rootpass
    disk:
      name: mysql-disk
      mountPath: /var/lib/mysql
      sizeGB: 10
    ports:                  # ✅ 3306ポートを明示
      - port: 3306
