services:
  - type: web
    name: fastapi-app
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: mysql-service
      - key: DB_USER
        value: sampleuser
      - key: DB_PASSWORD
        value: samplepass
      - key: DB_NAME
        value: sampledb
    healthCheckPath: /
