services:
  - type: web
    name: neon-fastapi-demo
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg2://user:yourpassword@ep-xxxx.us-west-2.aws.neon.tech:5432/neondb
      - key: PORT
        value: "10000"
